backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"
site_url: https://bluebridgesite.netlify.app

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
       file: "content/home.md"
        fields:
       - name: "body"
            label: "Main Content"
            widget: markdown
            buttons: ["bold", "italic", "heading-one", "heading-two", "link", "quote", "code"]
		 
		  
	
 