backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"
site_url: https://bluebridgesite.netlify.app

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
         - { label: "Content", name: "body", widget: "markdown" }  # WYSIWYG enabled
		 
		  - {name: "editable_div",
            label: "Main Text Block",
            widget: "markdown"}
		  
	
 